### ISSUE TITLE
Expanding the "y" and "dy" vectors in perturbations.c to include extra quantities

### ISSUE THREAD

**Issue by martendt** [lesgourg/class_public#108] opened 2016-08-04 11:27 UTC
Hello all, 
I'm relatively new to both using C and using CLASS, so please forgive me if I have made a simple error. 

I'm attempting to expand the vectors "y" and "dy" in the perturbations module to include other variables that I want to keep track of (for example, different photon bins for the delta_g value). However, if I try to increase the amount of allocation for these bins, by changing:
class_define_index(ppv->index_pt_delta_g,_TRUE_,index_pt,1);  (line ~3023, perturbations.c)
to:
class_define_index(ppv->index_pt_delta_g,_TRUE_,index_pt,2); 
In my mind, this creates an extra space for a value in the y and dy vectors, and index_pt is appropriately increased. Even if I don't ever reference this "new value" again, it should still compile and run correctly. However, when running it I get allocation errors referring to singular matrices in the generic evolver, or too small of step size. 

The errors do not always say the same thing, which leads me to believe it is an allocation issue. But for the life of me, I cannot figure out what I am missing. Your input is much appreciated!

Thanks, I really appreciate this code and everything you are doing for it!
Daniel

**Comment by ThomasTram** [comment] 2016-08-04 12:33
Hi Daniel,

the problem is not due to memory, but it is because you are (effectively) changing the differential system. The default solver is implicit, so it will need to factorise the Jacobian for the system. However, you have created a row and columns of zeros, so the LU decomposition fails. You could switch to an explicit solver by using evolver=0 in your ini file. I think this would then work.

*However*, you should never do what you are doing. Depending on what you want to accomplish, here is the correct procedure:
*) If you are interested in some perturbation as a function of time: Use k_outout_values and if the perturbation is not already available, add an entry in perturb_print_variables() and perturb_prepare_output()
*) If you are interested in the transfer function of some variable not already coded: This involves more steps but I can point you in the right direction if you need.
*) If you want to add some new physics, for instance momentum dependent photon distributions (!) you need to follow the steps of adding a new species to the code. (I have some slides explaining how to do this, let me know if you need them.)

Note that if you follow this procedure, the quantities of interest will automatically be available in the Python wrapper as well. (If you are not already using Ipython Notebook and the CLASS wrapper, now is a good time to start! See https://github.com/ThomasTram/iCLASS for some examples.)

Cheers,
Thomas

**Comment by martendt** [comment] 2016-08-04 16:16
Actually, I am interested in momentum dependent physics for the photons. I had figured the easiest way to do this was to bin the variables by the photon momentum value, and solve separate boltzmann equations depending on which photon bin we were looking at. What is the reason for adding a completely new species, as opposed to altering the current equations involving photons?


I would appreciate reading those slides, and thanks for the quick response!


Daniel

________________________________

**Comment by ThomasTram** [comment] 2016-08-09 16:04
Hi Daniel,

I have attached slides for adding a species to CLASS. In general it is better to add a new species instead of just modifying the existing species since you will be more likely to make the required changes in all necessary places, and you can use the unmodified species for crosschecks. However, in the case of photons I think it is actually better to modify the photon species directly as you were doing. You should follow the massive neutrino (NCDM) implementation closely. For instance, you should have a distribution function for the photons in the background, since all integrated quantities will be integrals over the distribution function. It is a very interesting project, but also difficult so good luck!
Cheers,
Thomas

[lecture13_exotic_species_and_testing.pdf](https://github.com/lesgourg/class_public/files/409318/lecture13_exotic_species_and_testing.pdf)

**Comment by martendt** [comment] 2016-08-10 03:40
Ok, thank you for the advice! I will look closely at the NCDM implementation. To be clear- is there any specific place I should look at in the NCDM notation that addresses the initial issue I've been having, with the increase in photon bins giving the evolver trouble?


Daniel

________________________________

**Comment by ThomasTram** [comment] 2016-08-10 12:15
I think the initial issue is caused by the following: Some places in the code the higher order multipoles (for the "first" momentum bin) are implicitly accessed by ````index_pt_delta_gamma+...````, for instance in for-loops. This happens when switching approximation schemes for instance. Also, many places it is implicitly assumed that the size of the photon temperature part has length ````l_max_g+1```` which is also not correct. You will need to go through all these cases of course.

Cheers,
Thomas

**Closed** 2016-11-16 11:35 UTC
