### ISSUE TITLE
Differences in P(k) with same total neutrino mass but different number of massive neutrinos

### ISSUE THREAD

**Issue by aoifeboyle** [lesgourg/class_public#70] opened 2015-11-23 08:48 UTC
Hello. I have been running CLASS with a total neutrino mass of 0.3 eV, divided among either 1 or 3 massive neutrinos. I've read that the level of suppression of the power spectrum should still be equal in these two cases, if the total neutrino mass is the same. But I get different results. This plot shows the relative difference between the matter power spectra for the two regimes:

![pk_comparison](https://cloud.githubusercontent.com/assets/5586399/11332517/96db9450-91c6-11e5-8fde-90116a76af53.png)

I am trying to calculate the derivative of the power spectrum with respect to the total neutrino mass, and this seems to make quite a significant difference. My two input parameter files are given below.

1) One massive neutrino
h = 0.707627
omega_ncdm = 0.00322095769809
omega_b = 0.023
omega_cdm = 0.124
k_per_decade_for_pk = 50.
k_per_decade_for_bao = 50.
N_ur = 2.0328
N_ncdm = 1.0
Omega_k = 0.0
YHe = 0.24
tau_reio = 0.1
output = mPk
modes = s
A_s = 2.66e-9
n_s = 0.95
P_k_max_h/Mpc = 1.0
z_pk = 0.3
m_ncdm = 0.3
write warnings = yes
write background = yes
write parameters = yes
deg_ncdm = 1.0

2) Three massive neutrinos
h = 0.707627
omega_ncdm = 0.000867023835087, 0.000960929783122, 0.00139300407988
omega_b = 0.023
omega_cdm = 0.124
k_per_decade_for_pk = 50.
k_per_decade_for_bao = 50.
N_ur = 0.00641
N_ncdm = 3.0
Omega_k = 0.0
YHe = 0.24
tau_reio = 0.1
output = mPk
modes = s
A_s = 2.66e-9
n_s = 0.95
P_k_max_h/Mpc = 1.0
z_pk = 0.3
m_ncdm = 0.0807546, 0.089501, 0.1297444
write warnings = yes
write background = yes
write parameters = yes
deg_ncdm = 1.0, 1.0, 1.0

For the values of N_ur, I followed the instructions given in point 4) of the explanatory input parameter file. 

Thank you for any suggestions.

Aoife

**Comment by ThomasTram** [comment] 2015-11-23 10:17
Hi Aoife,

that is a really nice figure, and it shows that the matter power spectrum is indeed weakly sensitive to the actual distribution of masses. Compare with Figure 5 in http://arxiv.org/pdf/1104.2935.pdf which shows percentage difference between normal and inverted neutrino hierarchy for the same total mass. What you have read is only approximatively correct: the main correction to P(k) comes from the (weighted) sum of masses, but there are corrections from the actual mass distribution. It also makes sense physically, since mass eigenstates with different masses would go nonrelativistic at different times, while mass eigenstates with the same mass would go non-relativistic at the same time. However, it is important to note that for a given total mass, we *know* the mass distribution up to a choice of hierarchy. So once the total mass MTOT>>sqrt(largest squared mass difference)~0.05eV, the three neutrinos will be effectively degenerate.

For you project, you could pick two limiting cases:
* 2 massless and 1 massive case: N_ncdm=1, m_ncdm = MTOT, deg_ncdm = 1.0
* 3 degenerate: M_ncdm=1, m_ncdm=MTOT/3, deg_ncdm=3.0
or you can do it for both hierarchies. But then you need a small code to compute the actual mass distribution for a given MTOT.

Cheers,
Thomas

**Comment by aoifeboyle** [comment] 2015-11-25 13:02
@ThomasTram Thank you so much for referring me to your paper - I hadn't seen it and it has been very helpful. Your explanation makes sense to me too. It's a relief to know my results are not wrong. 

One small thing is that I think there might be a typo on page 13. In the version I printed out, it says that Delta m_{32}^2 = +/- 2.4 x 10^{-3}. I think it should be Delta m_{31}^2? I'm not 100% sure though, and I don't think it makes a huge difference anyway since the mass difference between neutrinos 1 and 2 is so small compared to their mass differences with 3.

**Comment by ThomasTram** [comment] 2015-11-25 14:16
Hi, yes within the experimental error we have Delta m_{32}^2 = Delta m_{31}^2 = +/- 2.4 x 10^{-3}, so it is okay. I am closing the issue then.

Cheers,
Thomas

**Closed by ThomasTram** 2015-11-25 14:16 UTC

**Comment by aoifeboyle** [comment] 2015-11-25 22:45
@ThomasTram Sorry to bother you again - just one quick final issue I've noticed. I've been trying to reproduce figure 5 of the paper for a total neutrino mass of 0.1 eV. I get the following result:

![neutrinos](https://cloud.githubusercontent.com/assets/5586399/11411103/3d863f32-93cd-11e5-8781-63bee282f3e5.png)

It looks good apart from the fact that at low k values, the difference % is positive rather than negative. I've tried at higher mass values and it does then move towards 0 as in the paper. Could you please have a look at my input files below and see where I'm going wrong? I used the cl_ref.pre file for the precision parameters. 

For the normal hierarchy:
k_per_decade_for_pk = 100.
k_per_decade_for_bao = 100.
N_ur = 0.00641
N_ncdm = 3.0
output = mPk
P_k_max_h/Mpc = 1.0
m_ncdm = 0.022270, 0.023915, 0.053815

For the inverted hierarchy, the input file is the same apart from:
m_ncdm = 0.049005, 0.049775, 0.001220

I plotted the results as [P(k)(inv) - P(k)(nor)]/(P(k)(nor)) x 100.

I assumed that the default CLASS values for the other parameters would produce the same result but maybe that was a mistake? 

Thanks for your help.

**Comment by ThomasTram** [comment] 2015-11-26 09:56
Hi Aoife,

you are right. This (tiny!) difference at large scales is because the definition of the matter power spectrum P(k) has changes since version 1.0 which was used in the paper. Version 1.0 used by default just the total density contrast in the synchronous gauge. In order to have a more physical definition at large scales (remember that density contrast is a gauge-dependent quantity) we consider only species which are non-relativistic today, and we do a gauge transformation into a gauge co-moving with non-relativistic matter. This gauge transformation is different for the two cases, because the velocity divergence of ncdm today will depend on the exact mass.

The difference is tiny of course. The old behaviour can be reproduced by commenting out one line in perturbations.c, which in branch 2.4 is line 5135:
````
ppw->delta_m += 3. *ppw->pvecback[pba->index_bg_a]*ppw->pvecback[pba->index_bg_H] * ppw->theta_m/k2;
````

Cheers,
Thomas
